#------------------------Начальные значения для первой катушки-----------------------------------#
coilRadius1 : 2000    # Радиус самого маленького витка первой катушки, мм
loopCurrent1 : 1      # Ток первой катушки, Амперы
distance1 : 1000      # Расстояние между первыми витками катушки и центром координат
nLayers1 : 1          # Число слоёв первой катушки
layerStep1 : 1        # Расстояние между слоями, мм
nLoops1 : 1           # Число витков в нечетном слое первой катушки
loopStep1 : 1         # Расстояние между витками первой катушки, мм
isLeft1 : 1           # Является ли первая катушка левой (1если да, 0 если нет)
#------------------------Начальные значения для второй катушки-----------------------------------#
coilRadius2 : 2000    # Радиус самого маленького витка первой катушки, мм
loopCurrent2 : 1      # Ток первой катушки, Амперы
distance2 : 1000      # Расстояние между первыми витками катушки и центром координат
nLayers2 : 1          # Число слоёв первой катушки
layerStep2 : 1        # Расстояние между слоями, мм
nLoops2 : 1           # Число витков в нечетном слое первой катушки
loopStep2 : 1         # Расстояние между витками первой катушки, мм
isLeft2 : 0           # Является ли первая катушка левой (1если да, 0 если нет)
#------------------------------Начальные значения для сетки--------------------------------------#
planeSide : 5000      # Сторона квадратной секущей плоскости, мм
cellNumber : 150      # Число ячеек на сторону секущей плоскости (дискретизация)
zonesNumber : 1       # Число секущих плоскостей
dirPref : ""    # Путь к директории с рисунками
#------------------------------Начальные значения для синуса--------------------------------------#
freq1 : 2000          # Частота сигнала в левой каушке, Гц
freq2 : 3000          # Частота сигнала в правой катушке, Гц
periodsNumber: 2              # Число периодов катушки с наименьшей частотой, на котором смотрим поля
stepsNumber : 10           # Число интервалов дискретизации на один период катушки с наибольшей частотой
