#------------------------Начальные значения для первой катушки-----------------------------------#
isLeft1 : 1           # Является ли первая катушка левой (1если да, иначе 0)
coilWidth1 : 550      # Ширина самого маленького витка первой катушки, мм
coilHeight1 : 550     # Высота самого маленького витка первой катушки, мм
currentAmp1 : 1       # Амплитуда тока первой катушки, Амперы
nLayers1 : 1          # Число слоёв первой катушки
layerStep1 : 1        # Расстояние между слоями, мм
nLoops1 : 1           # Число витков в нечетном слое первой катушки
loopStep1 : 1         # Расстояние между витками первой катушки, мм
distance1 : 1000      # Расстояние между первыми витками катушки и центром координат
#------------------------Начальные значения для второй катушки-----------------------------------#
isLeft2 : 0           # Является ли вторая катушка левой (1если да, иначе 0)
coilWidth2 : 550      # Ширина самого маленького витка второй катушки, мм
coilHeight2 : 550     # Высота самого маленького витка второй катушки, мм
currentAmp2 : 2       # Амплитуда тока второй катушки, Амперы
nLayers2 : 1          # Число слоёв второй катушки
layerStep2 : 1        # Расстояние между слоями, мм
nLoops2 : 1           # Число витков в нечетном слое второй катушки
loopStep2 : 1         # Расстояние между витками второй катушки, мм
distance2 : 1000      # Расстояние между первыми витками катушки и центром координат
#------------------------------Начальные значения для сетки--------------------------------------#
planeSide : 5000      # Сторона квадратной секущей плоскости, мм
cellNumber : 150      # Число ячеек на сторону секущей плоскости (дискретизация)
zonesNumber : 1       # Число секущих плоскостей
dirPref : ""    # Путь к директории с рисунками
#------------------------------Начальные значения для синуса--------------------------------------#
freq1 : 2000          # Частота сигнала в левой каушке, Гц
freq2 : 3000          # Частота сигнала в правой катушке, Гц
periodsNumber: 2              # Число периодов катушки с наименьшей частотой, на котором смотрим поля
stepsNumber : 20           # Число интервалов дискретизации на один период катушки с наибольшей частотой 
